services:
  db:
    container_name: postgresql
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: wow
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: my
    ports:
      - "5432:5432"